directories:
  output: release
  buildResources: build
appId: com.youtube.downloader
productName: YouTube Downloader
files:
  - filter:
      - dist/**/*
      - binaries/**/*
      - package.json
win:
  target: nsis
electronVersion: 37.10.3
